### ISSUE TITLE
Elegant Hubris Slum Lord search doesn't work

### ISSUE THREAD

**Issue by Neltisen** [KeshHere/POE-Timeless-Jewel-Finder#1]
Trying to find Elegant Hubris Slkum Lord near agnostic, nodes:
Arcane Capacitor
Faith and Steel
Overcharge
Endurance
Devotion
Smashing Strikes
Sanctum of Thought
Light of Divinity
Holy Dominion
Divine Fervour

Unfortunately it doesn't find a single Slum Lord there.

**Comment by KeshHere** [comment]
Solved! Thank you for the report.
