### ISSUE TITLE
Chrome refuses to DL latest release, "failed - virus detected"

### ISSUE THREAD

**Issue by SpecificallyVague** [KeshHere/POE-Timeless-Jewel-Finder#2]
don't even get an option to "keep file anyways" or whatever

something must be very sus for chrome to not even give me an option :(

**Comment by KeshHere** [comment]
Can you try different browser, chrome sometimes is very strict with downloading.exe files directly even when it is inside zip.

**Comment by KeshHere** [comment]
Just downloaded using chrome (had to say yes to keep the file but it was possible)

**Comment by KeshHere** [comment]
If it doesn't work out still. Download the code(.au3 file), download 2 zips from main page[not releases page because that zip contains exe file as well] containing 5 CSVs.
After that install AutoIt3 to run the code aka .au3 file.
