### ISSUE TITLE
Elegant Hubris Mod Missing

### ISSUE THREAD

**Issue by ShrekIII** [KeshHere/POE-Timeless-Jewel-Finder#6]
Seems like the "Supreme Ostentation" mod is missing...

**Comment by KeshHere** [comment]
That is not a notable passive as far as I know, It is Keystone passive. So any jewel with "Commissioned # coins to commemorate Caspiro" will have that keystone passive irrespective of the number
https://www.poewiki.net/wiki/Elegant_Hubris
Feel free to open this or make new issue if I misunderstood something.
