### ISSUE TITLE
update for 3.20

### ISSUE THREAD

**Issue by Desm0ndMilles** [KeshHere/POE-Timeless-Jewel-Finder#8]
Will you update PT for 3.20? This prog to awesome, dont wanna use visol now. 
If u dont want update, can u say how to upgrade the pt

**Comment by KeshHere** [comment]
Oh hey, thanks for the interest. I assumed most of the players either use vilsol or pob now to find the timeless jeweller. I will try to update it this week to get it working and update this thread. Cheers.

**Comment by KeshHere** [comment]
Updated data for 3.20, let me know if you run into any error. Cheers.
