### ISSUE TITLE
Data Inaccuracy for the "Ash, Frost and Storm " Node

### ISSUE THREAD

**Issue by halfacandan** [KeshHere/POE-Timeless-Jewel-Finder#9]
Hi

I noticed an issue with the data for the "Ash, Frost and Storm " Node. I suspect that it may have changed since the 3.22 release. Here's a worked example:

**Dataset:** LethalPrideSeeds.csv
**Seed:** 11894
**Summary of  "Double Damage" nodes:**
Notable | Effect
-- | --
Ash Frost and Storm | +_double_damage
Blacksmiths Clout | +_double_damage
Blunt Trauma | +_double_damage
Dervish | +_double_damage
Golem Commander | +_double_damage
Potent Connections | +_double_damage
Prismatic Skin | +_double_damage
Ribcage Crusher | +_double_damage
Throatseeker | +_double_damage
Totemic Zeal | +_double_damage

In-game Nodes:
 - Ash, Frost and Storm - +20 Strength
 - Potent Connections  - Double Damage
 -  Totemic Zeal - Double Damage

![ashfroststorm](https://github.com/KeshHere/POE-Timeless-Jewel-Finder/assets/8378433/5f147a27-6927-4291-9391-0a2357d9fa90)

You can also see the in-game nodes in this tool:
https://vilsol.github.io/timeless-jewels/tree?jewel=2&conqueror=Akoya&seed=11894&location=6230&mode=seed

**Comment by KeshHere** [comment]
Hey, thanks for the info. It is solved now in latest CSVs.
